### ISSUE TITLE
AttributeError: 'Lumberjack' object has no attribute 'land_based'

### ISSUE THREAD

**Issue by Danquebec** [JarvisTheJelly/villager-sim#8]
Running Python 2.7.13 on Linux Fedora 25, when I try to start UpdatingVillagerSim.py, I get the following error:
```
Traceback (most recent call last):
  File "UpdatingVillagerSim.py", line 103, in <module>
    run(bool(int(sys.argv[1])), int(sys.argv[2]))
  File "UpdatingVillagerSim.py", line 36, in run
    game_world = World.World((world_size, world_size), screen_size)
  File "/home/daniel/programmation/projets_d_autres_personnes/villager-sim-master/World.py", line 51, in __init__
    self.new_world(tile_dimensions)
  File "/home/daniel/programmation/projets_d_autres_personnes/villager-sim-master/World.py", line 191, in new_world
    self.populate()
  File "/home/daniel/programmation/projets_d_autres_personnes/villager-sim-master/World.py", line 231, in populate
    new_ent.brain.set_state(start[key]["state"])
  File "/home/daniel/programmation/projets_d_autres_personnes/villager-sim-master/aitools/StateMachine.py", line 45, in set_state
    self.active_state.entry_actions()
  File "/home/daniel/programmation/projets_d_autres_personnes/villager-sim-master/Lumberjack.py", line 71, in entry_actions
    BaseFunctions.random_dest(self.lumberjack)
  File "/home/daniel/programmation/projets_d_autres_personnes/villager-sim-master/BaseFunctions.py", line 26, in random_dest
    walk = TileFuncs.get_tile(entity.world, possible_dest).walkable == entity.land_based
AttributeError: 'Lumberjack' object has no attribute 'land_based'
```

**Comment by najarvis** [comment]
Sorry about this, are you on the master branch? We have been (were) working on the Competent AI branch and I don't think we've updated master in a long time.

**Comment by Danquebec** [comment]
Yes, that’s the master. Should I download TheAIReform instead? Thank you for your answer.

**Comment by najarvis** [comment]
I think the branch you want is 'CompetentAI.' Sorry for the late reply. I will try to do a pull request if I get time.

**Comment by najarvis** [comment]
I have made merged the two branches and have deleted CompetentAI. Please pull the newest changes on the master branch and let me know if that fixed it.

**Comment by Danquebec** [comment]
Ok, great, it’s running. Thanks!

Btw, the link http://proceduralintelligence.com/projects.php on this page https://www.pygame.org/project/2882 is dead.

**Comment by najarvis** [comment]
Awesome, thanks for letting me know. You should just be able to remove the
".php", I've moved to different hosts and updated the website.

Nick
